service: aws-nodejs # NOTE: update this with your service name

custom: 
  region: 'eu-west-1'
  stage: 'dev'



provider:
  name: aws
  apiKeys:
    - myApiKey  
  runtime: nodejs6.10
  region: ${self:custom.region} 
  environment:
    REGION: ${self:custom.region} 
    USER_POOL_ID: ${file(./serverless.env.yml):${self:custom.stage}.USER_POOL_ID}
    CLIENT_ID: ${file(./serverless.env.yml):${self:custom.stage}.CLIENT_ID}

functions:
  register:
    handler: cognito/register.register
    events:
      - http:
          path: cognito/user/create
          method: post
          cors: true
          private: true